#######################################################################################################################
############################################# Instructions #################################################

# Instructions function 

show_instructions <- function() {
  
  ui <- fluidPage(
    titlePanel("Instructions"),
    
    fluidRow(
      column(
        width = 12,
        
        h3("General Details"),
        
        tags$ul(
          tags$li("You do not need to modify the code during execution."),
          tags$li("Interactive windows will open to guide you (e.g. parameter input)."),
          tags$li("Follow the instructions in each window carefully to avoid errors."),
          tags$li(tags$strong("Press 'Submit' to save your choices.")),
          tags$li("After submission, the window will turn grey — you can safely close it.")
        ),
        
        hr(),
        
        h3("Execution advice"),
        
        tags$ul(
          tags$li("For better understanding, beginners are encouraged to run the script ",
                  tags$strong("step by step"),
                  " (most steps simply apply a function and return results)."),
          tags$li("Alternatively, you can run the entire script using ",
                  tags$strong("Ctrl + A"),
                  " then ",
                  tags$strong("Ctrl + Enter"),
                  ".")
        ),
        
        div(
          style = "background-color:#ffecec; border-left:4px solid #e74c3c; padding:12px; margin-top:10px;",
          tags$strong("IMPORTANT : "),
          "Press 'Submit' only when the desired figure/result is displayed. ",
          "This determines what gets saved."
        ),
        
        hr(),
        
        h3("Partial execution"),
        
        div(
          style = "
            background-color: #fff4e5;
            border-left: 4px solid #f5a623;
            padding: 16px 20px;
            border-radius: 4px;
            margin-top: 10px;
          ",
          h4(style = "margin-top: 0; color: #b26a00;",
             "⚠ Optional advanced usage (experienced R users only)"),
          
          tags$ul(
            tags$li("You can run only specific parts of the pipeline if needed."),
            tags$li("Load the ", tags$strong("RData checkpoint environment"),
                    " corresponding to the desired step. Several backup operations are performed during the project."),
            tags$li("Re-run only the relevant section of the code."),
            tags$li(tags$strong("Incorrect use may lead to inconsistent results or errors."))
          )
        ),
        
        br(),
        
        actionButton("submit", "Submit", class = "btn-success")
      )
    )
  )
  
  server <- function(input, output, session) {
    observeEvent(input$submit, {
      stopApp(TRUE)
    })
  }
  
  runApp(shinyApp(ui, server), launch.browser = TRUE)
}

show_instructions() # Show the instructions to the operator

#######################################################################################################################
####################################### Creation of the file architecture #################################################

get_path_gui <- function() {
  
  ui <- fluidPage(
    titlePanel("Select the Project Root Directory (exemple : C:/Users/EXT-PMarquet1/Test_16-02-26)"),
    
    sidebarLayout(
      sidebarPanel(
        textInput(
          inputId = "path",
          label = "Enter the folder path :",
          value = ""
        ),
        
        tags$div(
          class = "alert alert-info",
          style = "margin-top: 10px;",
          icon("circle-info"),
          strong(" The following files will be created in the root directory : "),
          "mzML, Results, Metadata, Rdata_checkpoint"
        ),
        
        actionButton("submit", "Submit", class = "btn-success")
      ),
      mainPanel(
        h4("What is a root directory ?"),
        p("A ", strong("root directory"), " (or root path) is the top-level folder of your project. 
          It serves as the common starting point from which all project files and subfolders are organized."),
        p("All working files and output folders generated by this application will be created 
          directly inside this directory. If the folder does not exist, it will be created automatically.")
      )
    )
  )
  
  server <- function(input, output, session) {
    
    # Return path when Submit is clicked
    
    observeEvent(input$submit, {
      
      if(nchar(trimws(input$path)) == 0){
        
        showNotification("Path cannot be empty.", type = "error")
        
        return(NULL)
        
      }
      
      stopApp(input$path)
    })
    
  }
  
  runApp(shinyApp(ui, server), launch.browser = TRUE)
}

# Principal pathway

main_folder <- get_path_gui()

# Main folder creation

if (!dir.exists(main_folder)) {
  dir.create(main_folder)
}

# Level 0 folders

folders_lvl0 <- c("mzML", "Results", "Metadata","Rdata_checkpoint")

# Level 1 inside Results

results_lvl1 <- c("Parameters", "Data", "Charts")

# Level 2 inside Parameters/Data/Charts

subfolders_lvl2 <- c("1_Pre-processing",
                     "2_Processing",
                     "3_Annotation",
                     "4_Unsupervised_analyses",
                     "5_Supervised_analyses")

processing_sub <- c(
  "01_Quality Control",
  "02_RT_filter",
  "03_Sample_Outlier_Exclusion",
  "04_Missing_Value_Filter",
  "05_Missing_Value_Imputation",
  "06_Permissive_CV_pre_LOESS",
  "07_Intra_Batch_Drift_Correction",
  "08_Normalization",
  "09_Strict_CV",
  "10_Data_Transformation",
  "11_Data_Scaling"
)

# Create level 0 folders

for (lvl0 in folders_lvl0) {
  
  path_lvl0 <- file.path(main_folder, lvl0)
  
  if (!dir.exists(path_lvl0)) {
    dir.create(path_lvl0)
  }
}

# mzML subfolders

mzml_sub <- c("mzML_data", "mzML_diluted_QC")

for (sub in mzml_sub) {
  
  path <- file.path(main_folder, "mzML", sub)
  
  if (!dir.exists(path)) {
    dir.create(path)
  }
}

# Results structure

for (sub1 in results_lvl1) {
  
  path_lvl1 <- file.path(main_folder, "Results", sub1)
  
  if (!dir.exists(path_lvl1)) {
    dir.create(path_lvl1)
  }
  
  for (sub2 in subfolders_lvl2) {
    
    path_lvl2 <- file.path(path_lvl1, sub2)
    
    if (!dir.exists(path_lvl2)) {
      dir.create(path_lvl2)
    }
    
    # Add extra subfolders depending on sub2
    
    if (sub2 == "2_Processing") {
      for (sub3 in processing_sub) {
        
        path_sub3 <- file.path(path_lvl2, sub3)
        
        if (!dir.exists(path_sub3)) {
          dir.create(path_sub3)
        }
      }
    }
  }
}


# Sub-folder names (in /mzML_data)

mzML_folder <- paste0(main_folder,"/mzML/mzML_data") # mzML folder

# Warning function 

show_warning <- function(mzML_folder) {
  
  ui <- fluidPage(
    tags$head(tags$style(HTML("
      body { background-color: #f8f9fa; }
      .main-panel { background: white; border-radius: 10px; padding: 30px; margin-top: 20px; box-shadow: 0 2px 8px rgba(0,0,0,0.1); }
      .count-box { background: #e8f4fd; border-left: 5px solid #2196F3; padding: 12px 18px; border-radius: 4px; margin-bottom: 10px; }
      .count-number { color: #2196F3; font-weight: bold; }
      .warn-box { background: #fff8e1; border-left: 5px solid #ffc107; padding: 12px 18px; border-radius: 4px; margin-bottom: 10px; }
      .red-box { background: #fff0f0; border-left: 5px solid #e53935; padding: 12px 18px; border-radius: 4px; margin: 10px 0; }
      .btn-continue { background-color: #2196F3; color: white; border: none; padding: 10px 30px; border-radius: 5px; }
      .btn-continue:hover { background-color: #1976D2; color: white; }
    "))),
    
    fluidRow(
      column(width = 8, offset = 2,
             div(class = "main-panel",
                 h2("\U0001F4C2 Action Required", style = "color:#333; margin-bottom:25px;"),
                 
                 uiOutput("mzml_count"),
                 
                 div(class = "red-box",
                     h3(tags$b("\U0001F4CC Important:"),
                        " Please place all mzML files ",
                        tags$b("used in your study and acquired with the same ionization polarity"),
                        " in the 'mzML' folder created by the pipeline."
                     )
                 ),
                 
                 uiOutput("non_mzml_warning"),
                 
                 div(class = "red-box",
                     h3(tags$b("\U0001F6A8 Reminder :"),
                        tags$span(" Equilibration QCs and Diluted QCs must not under any circumstances be placed in this folder.
               A specific folder has been created for them. If you do not have diluted QCs, this is not a problem.",
                                  style = "color:#c62828;"))
                 ),
                 
                 br(),
                 checkboxInput("confirmed", 
                               label = tags$b("I confirm that all mzML files are correctly placed in the folder."), 
                               value = FALSE),
                 uiOutput("checkbox_error"),
                 
                 br(),
                 h4("Once all files are copied, click Continue. (you can close the page afterward)"),
                 br(),
                 actionButton("continue", "\u2713 Continue", class = "btn-continue")
             )
      )
    )
  )
  
  server <- function(input, output, session) {
    
    scan_files <- reactive({
      invalidateLater(1000, session)
      all_files  <- list.files(mzML_folder, full.names = FALSE)
      mzml_files <- all_files[grepl("\\.mzML$", all_files, ignore.case = TRUE)]
      list(n_mzml = length(mzml_files), n_non_mzml = length(setdiff(all_files, mzml_files)))
    })
    
    output$mzml_count <- renderUI({
      div(class = "count-box",
          h3(tags$span(class = "count-number", scan_files()$n_mzml),
             " mzML files detected in the mzML folder.")
      )
    })
    
    output$non_mzml_warning <- renderUI({
      if (scan_files()$n_non_mzml != 0)
        div(class = "warn-box",
            h3(tags$span("\u26a0", style = "color:#ffc107;"),
               tags$span(paste0(" ", scan_files()$n_non_mzml, " non-mzML files detected in the mzML folder."),
                         style = "color:#e65100; font-weight:bold;"))
        )
    })
    
    clicked <- reactiveVal(FALSE)
    output$checkbox_error <- renderUI({
      if (clicked() && !input$confirmed)
        tags$p("\u274c You must check the confirmation box before continuing.", 
               style = "color:red; font-weight:bold;")
    })
    observeEvent(input$continue, { clicked(TRUE); req(input$confirmed); stopApp(TRUE) })
  }
  
  runApp(shinyApp(ui, server), launch.browser = TRUE)
}

show_warning(mzML_folder) # Show the warning to the operator


#################################################################################################################
#######################################       File Pathway      #################################################

# File Pathway (# Replace with your own pathway)

param_folder <- paste0(main_folder, "/Results/Parameters") # Parameters folder

data_folder <- paste0(main_folder, "/Results/Data") # Data folder

chart_folder <- paste0(main_folder, "/Results/Charts") # Chart folder

Save_secu_folder <- paste0(main_folder, "/Rdata_checkpoint") # Save security folder

metadata_folder <- paste0(main_folder, "/Metadata") # Metadata folder


##########################################################################################################
####################################### Metadata Importation #################################################

# Example Creation

create_metadata_example(metadata_folder)

# Function to load the Metadata table

get_metadata_table <- function(metadata_folder) {
  
  ui <- fluidPage(
    
    tags$head(
      tags$style(HTML("
 
        hr {
          border: none;
          border-top: 1px solid #e3e7ec;
          margin: 20px 0;
        }
 
        .section-hint {
          font-size: 12.5px;
          color: #8a93a0;
          margin-bottom: 14px;
          font-style: italic;
        }
 
        details.section-card {
          background: #fbfcfd;
          border: 1px solid #e3e7ec;
          border-radius: 8px;
          margin-bottom: 8px;
          overflow: hidden;
        }
 
        details.section-card summary {
          cursor: pointer;
          list-style: none;
          padding: 10px 14px;
          font-size: 14px;
          font-weight: 600;
          color: #1f2d3d;
          background: #f1f4f8;
          display: flex;
          align-items: center;
        }
        details.section-card summary::-webkit-details-marker { display: none; }
        details.section-card summary::before {
          content: '\u25B8';
          color: #2C7BE5;
          margin-right: 8px;
          display: inline-block;
          transition: transform 0.15s ease;
        }
        details.section-card[open] summary::before { transform: rotate(90deg); }
        details.section-card[open] summary { border-bottom: 1px solid #e3e7ec; }
 
        .section-card-body {
          padding: 12px 18px;
          font-size: 13.5px;
          line-height: 1.65;
          color: #3a3f44;
        }
        .section-card-body ul { margin: 6px 0 4px 18px; padding: 0; }
        .section-card-body li { margin-bottom: 5px; }
 
      "))
    ),
    
    titlePanel("Load the Metadata Table"),
    
    sidebarLayout(
      sidebarPanel(
        fileInput("file", "Upload CSV or Excel file",
                  accept = c(".csv", ".xlsx", ".xls")),
        br(),
        actionButton("submit", "Submit", class = "btn-success")
      ),
      
      mainPanel(
        tabsetPanel(
          
          # ── Tab 1 : Instructions ──────────────────────────────────────
          
          tabPanel(
            title = "Instructions",
            div(
              style = "height: 85vh; overflow-y: auto; padding-right: 10px; padding-top: 16px;",
              
              p(class = "section-hint",
                "Click a section below to expand its detailed explanation."),
              
              hr(),
              
              # Example spreadsheet
              
              div(
                style = paste(
                  "background: #eaf6ee;",
                  "border: 1.5px solid #34a853;",
                  "border-left: 5px solid #34a853;",
                  "border-radius: 8px;",
                  "padding: 14px 18px;",
                  "margin-bottom: 16px;",
                  "display: flex;",
                  "align-items: flex-start;",
                  "gap: 12px;"
                ),
                
                tags$span("\U0001F4C2", style = "font-size: 22px; line-height: 1.4; flex-shrink: 0;"),
                div(
                  tags$strong(
                    "Example Excel spreadsheet provided",
                    style = "font-size: 14px; color: #1a6e30; display: block; margin-bottom: 6px;"
                  ),
                  tags$ul(
                    style = "margin: 0; padding-left: 18px; font-size: 13.5px; color: #2d4a33; line-height: 1.7;",
                    tags$li(
                      tags$span("An example file is available separately to guide formatting",
                                style = "color: #1a7a35; font-weight: 500;")
                    ),
                    tags$li(
                      tags$code("your_folder/Metadata/Metadata_Example.xlsx",
                                style = "background:#d6edd9; padding: 1px 5px; border-radius: 4px; font-size: 12.5px;")
                    ),
                    tags$li("Copy this file to create your own metadata and minimise formatting errors.")
                  )
                )
              ),
              
              # ReDU informations
              
              div(
                style = paste(
                  "background: #eef4fb;",
                  "border: 1.5px solid #2C7BE5;",
                  "border-left: 5px solid #2C7BE5;",
                  "border-radius: 8px;",
                  "padding: 12px 18px;",
                  "margin-bottom: 16px;",
                  "display: flex;",
                  "align-items: flex-start;",
                  "gap: 12px;"
                ),
                tags$span("\U0001F517", style = "font-size: 20px; line-height: 1.5; flex-shrink: 0;"),
                div(
                  tags$strong("Metadata format inspired by ReDU (GNPS2)",
                              style = "font-size: 13.5px; color: #1a4a8a; display: block; margin-bottom: 4px;"),
                  tags$span(
                    "The structure of this metadata table is strongly inspired by the ",
                    tags$a("ReDU format (GNPS2 Documentation)",
                           href   = "https://wang-bioinformatics-lab.github.io/GNPS2_Documentation/ReDU_overview/",
                           target = "_blank",
                           style  = "color: #2C7BE5; font-weight: 500;"),
                    ". Adopting a compatible format facilitates data sharing and downstream reuse in public repositories.",
                    style = "font-size: 13px; color: #2d3f55; line-height: 1.6;"
                  ),
                  
                  tags$strong("Column colour code", style = "display:block; margin-bottom:8px;"),
                  tags$ul(
                    tags$li(
                      tags$span("■ Red", style = "color:#EE0000; font-weight:bold;"),
                      " — required columns, directly read by the application (Country, YearOfAnalysis, filename, SampleName, SampleType, Group, OrderInjection, PairedID, Longitudinal_TimePoint, Batch, Hypothesis_1)."
                    ),
                    tags$li(
                      tags$span("■ Cyan", style = "color:#008B8B; font-weight:bold;"),
                      " — recommended ReDU/GNPS2 format columns, not used by the application but strongly recommended for future submission to MassIVE."
                    )
                  ),
                  tags$p(
                    tags$strong("It is strongly recommended to enrich the metadata"),
                    " with as many ReDU-compatible columns as possible (beyond those already included in the example), ",
                    "to maximize the reusability of your data when submitting to a public repository. ",
                    "The complete list of categories and allowed terms is maintained by GNPS2 : ",
                    tags$a(
                      "ReDU categories",
                      href = "https://docs.google.com/spreadsheets/d/10U0xnJUKa_mD0H_9suH1KJAlJD9io9e4chBX8EAHneE/edit?gid=1856413163#gid=1856413163",
                      target = "_blank"
                    ),
                    " and ",
                    tags$a(
                      "allowed terms",
                      href = "https://docs.google.com/spreadsheets/d/10U0xnJUKa_mD0H_9suH1KJAlJD9io9e4chBX8EAHneE/edit?gid=155945972#gid=155945972",
                      target = "_blank"
                    ),
                    "."
                  )
                )
              ),
              
              # Required metadata format — open by default
              
              tags$details(class = "section-card",
                           tags$summary("Required metadata format"),
                           div(class = "section-card-body",
                               tags$ul(
                                 tags$li("The file must contain at least the following columns:"),
                                 tags$ul(
                                   tags$li("SampleName"),
                                   tags$li("SampleType"),
                                   tags$li("Group"),
                                   tags$li("OrderInjection"),
                                   tags$li("PairedID"),
                                   tags$li("Longitudinal_TimePoint"),
                                   tags$li("Batch"),
                                   tags$li("Hypothesis_1")
                                 ),
                                 tags$li(tags$span(
                                   "Column names must match EXACTLY (case-sensitive, no extra spaces)",
                                   style = "color:red;"
                                 ))
                               )
                           )
              ),
              
              # SampleType
              
              tags$details(class = "section-card",
                           tags$summary("SampleType definition"),
                           div(class = "section-card-body",
                               tags$ul(
                                 tags$li("This column defines the biological role of each sample"),
                                 tags$li("Allowed values : Bio, pool_QC, blank_analysis, pool_Qcdil"),
                                 tags$li(tags$span(
                                   "No missing values allowed",
                                   style = "color:red;"
                                 ))
                               )
                           )
              ),
              
              # Group
              
              tags$details(class = "section-card",
                           tags$summary("Group definition"),
                           div(class = "section-card-body",
                               tags$ul(
                                 tags$li("Defines the experimental condition of each BIO sample (e.g. Control, Treatment_A, Treatment_B)"),
                                 tags$li("Used during missing value filtering to evaluate per-group detection rates — a feature is retained if at least one group meets the missing value threshold, regardless of its global BIO proportion"),
                                 tags$li(tags$span(
                                   "No missing values allowed for BIO samples",
                                   style = "color:red;"
                                 )),
                                 tags$li(tags$span(
                                   "Please note that this column will not be used as a hypothesis. To do so, simply duplicate it to create a hypothesis column.",
                                   style = "color:red;"
                                 ))
                               )
                           )
              ),
              
              # PairedID
              
              tags$details(class = "section-card",
                           tags$summary("PairedID definition"),
                           div(class = "section-card-body",
                               tags$ul(
                                 tags$li("This column links samples belonging to the same biological subject across conditions or time points"),
                                 tags$li("Each unique subject must receive a consistent identifier throughout the dataset (e.g. Subject_01, Subject_02 or P1, P2, P3)"),
                                 tags$li("It is used to apply paired or repeated-measures statistical models that account for intra-subject variability"),
                                 tags$li("In a paired design, each PairedID must appear at least twice — once per condition or time point being compared"),
                                 tags$li(tags$span(
                                   "Leave this column empty if your design is unpaired (independent groups).",
                                   style = "color:blue;"
                                 )),
                                 tags$li(tags$span(
                                   "A PairedID filled without a Longitudinal_TimePoint will be treated as technical replicates, not longitudinal samples.",
                                   style = "color:orange;"
                                 )),
                                 tags$li(tags$span(
                                   "Each PairedID must be unique per subject — do not reuse the same ID across unrelated individuals.",
                                   style = "color:red;"
                                 ))
                               )
                           )
              ),
              
              # Longitudinal_TimePoint
              
              tags$details(class = "section-card",
                           tags$summary("Longitudinal_TimePoint definition"),
                           div(class = "section-card-body",
                               tags$ul(
                                 tags$li("This column defines the temporal structure of longitudinal samples"),
                                 tags$li("It indicates when each biological sample was collected for a given subject (e.g. Baseline, Month_3, Month_6 or T0, T1, T2)"),
                                 tags$li("This variable is used to distinguish repeated measurements within the same subject over time"),
                                 tags$li("It is essential for paired or repeated-measures statistical models (e.g. linear mixed models) to account for intra-subject correlation"),
                                 tags$li("Each PairedID can appear multiple times, but each combination of PairedID + Longitudinal_TimePoint must be meaningful and biologically consistent"),
                                 tags$li(tags$span(
                                   "This column can be left empty.",
                                   style = "color:blue;"
                                 )),
                                 tags$li(tags$span(
                                   "If a PairedID is provided without a corresponding Longitudinal_TimePoint, samples sharing the same PairedID
                                   will be treated as technical replicates rather than longitudinal samples.",
                                   style = "color:orange;"
                                 ))
                               )
                           )
              ),
              
              # Hypothesis structure
              
              tags$details(class = "section-card",
                           tags$summary("Hypothesis structure"),
                           div(class = "section-card-body",
                               tags$ul(
                                 tags$li("The Hypothesis columns are intended to test a single scientific question"),
                                 tags$li("You are expected to assign a class to the samples that will be tested against this hypothesis"),
                                 tags$li("You can define multiple hypothesis columns (e.g. Hypothesis_1, Hypothesis_2, ...)"),
                                 tags$li("Each hypothesis will be tested independently")
                               )
                           )
              ),
              
              # Data integrity rules
              
              tags$details(class = "section-card",
                           tags$summary("Data integrity rules"),
                           div(class = "section-card-body",
                               tags$ul(
                                 tags$li("No missing values in SampleType"),
                                 tags$li("Batch column must reflect experimental acquisition batches"),
                                 tags$li("PairedID is required for paired designs, leave the boxes empty if not applicable"),
                                 tags$li("OrderInjection must reflect injection order for QC correction"),
                                 tags$li(tags$span(
                                   "Equilibration QCs must not under any circumstances be placed in the metadata",
                                   style = "color:red;"
                                 ))
                               )
                           )
              ),
              
              # Recommendations
              
              tags$details(class = "section-card",
                           tags$summary("Recommendations"),
                           div(class = "section-card-body",
                               tags$ul(
                                 tags$li("Ensure balanced groups for reliable PLS-DA / OPLS-DA"),
                                 tags$li("Include QC samples regularly : 1 at the start and one at the end / + 1 for every 10 samples"),
                                 tags$li("Check metadata consistency before launching analysis")
                               )
                           )
              )
            )
          ),
          
          # ── Tab 2 : Example table ────────────────────────────────────
          
          tabPanel(
            title = "Example table",
            tableOutput("example")
          ),
          
          # ── Tab 3 : Preview ──────────────────────────────────────────
          
          tabPanel(
            title = "Preview of uploaded table",
            reactableOutput("preview")
          )
        )
      )
    )
  )
  
  # ── Server ─────────────────────────────────────────────────────────────
  server <- function(input, output, session) {
    
    sample_data <- reactive({
      
      req(input$file)
      ext <- tools::file_ext(input$file$name)
      
      if (ext %in% c("csv")) {
        
        df <- read.csv(input$file$datapath, stringsAsFactors = FALSE)
        
      } else if (ext %in% c("xlsx", "xls")) {
        
        df <- read_excel(input$file$datapath)
        
      } else {
        
        showNotification("Invalid file type. Please upload CSV or Excel.", type = "error")
        return(NULL)
      }
      
      # Check required columns
      
      required_columns <- c("SampleName", "SampleType", "Group", "OrderInjection",
                            "PairedID", "Longitudinal_TimePoint", "Batch", "Hypothesis_1")
      
      missing_columns <- setdiff(required_columns, colnames(df))
      
      if (length(missing_columns) > 0) {
        showNotification(
          paste0("Missing required column(s): ", paste(missing_columns, collapse = ", ")),
          type = "error"
        )
        return(NULL)
      }
      
      # Check SampleType validity
      
      valid_sample_types <- c("Bio", "pool_QC", "blank_analysis", "pool_Qcdil")
      
      if (!all(df$SampleType %in% valid_sample_types)) {
        invalid_values <- unique(df$SampleType[!df$SampleType %in% valid_sample_types])
        showNotification(
          paste0("Invalid SampleType detected : ", paste(invalid_values, collapse = ", ")),
          type = "error"
        )
        return(NULL)
      }
      
      df
    })
    
    output$example <- renderTable({
      path <- file.path(metadata_folder, "Metadata_Example.xlsx")
      if (file.exists(path)) {
        readxl::read_excel(path)
      } else {
        data.frame(Message = "Example file not found — run create_metadata_example() first.")
      }
    })
    
    output$preview <- reactable::renderReactable({
      reactable(
        sample_data(),
        searchable    = TRUE,
        sortable      = TRUE,
        defaultPageSize = 15,
        highlight     = TRUE,
        bordered      = TRUE,
        rownames      = FALSE
      )
    })
    
    observeEvent(input$submit, {
      req(sample_data())
      stopApp(sample_data())
    })
  }
  
  runApp(shinyApp(ui, server), launch.browser = TRUE)
}

# Safety Loop

validate <- FALSE

while(!isTRUE(validate)){
  
  # Sample-group table loading
  
  metadata_table <- get_metadata_table(metadata_folder)
  
  #######################################     Sample Type    ###################################################
  
  # Names according to sample type
  
  bio_names <- metadata_table$SampleName[metadata_table$SampleType == "Bio"]
  
  qc_names <- metadata_table$SampleName[metadata_table$SampleType == "pool_QC"]
  
  blank_names <- metadata_table$SampleName[metadata_table$SampleType == "blank_analysis"]
  
  
  # Warning function 
  
  show_warning_3 <- function() {
    
    ui <- fluidPage(
      titlePanel("Action Required"),
      
      fluidRow(
        column(
          width = 12,
          h3("Please, place the correspondence file in the specific file (Metadata) in order to facilitate the study traceability."),
          br(),
          h3("Once all files are copied, click Continue. (you can close the page afterward)"),
          br(),
          div(
            class = "alert alert-success",
            h3("\U00002705 IMPORTANT"),
            h4("If no other Shiny interface opens automatically, the initialization script has finished successfully. Please return to the R code.")
          ),
          br(),
          actionButton("continue", "Continue")
        )
      )
    )
    
    server <- function(input, output, session) {
      
      observeEvent(input$continue, {
        stopApp(TRUE)
      })
      
    }
    
    runApp(shinyApp(ui, server), launch.browser = TRUE)
  }
  
  show_warning_3() # Show the warning to the operator
  
  
  ###################################################################################
  ############################   mzML Listing and Code Security Verification
  
  # mzML listing (total)
  
  file_list_tot <- list.files(path = mzML_folder, pattern = "\\.mzML$", full.names = TRUE)
  
  cat("Files found :\n")
  print(file_list_tot)
  
  # Security check: Number of files and file names = number and names of samples in the metadata table 
  
  mzml_files_names <- tools::file_path_sans_ext(basename(file_list_tot))
  
  metadata_names <- metadata_table$SampleName[
    !is.na(metadata_table$SampleType) &
      metadata_table$SampleType != "pool_Qcdil"
  ]
  
  mzml_missing_in_metadata <- setdiff(mzml_files_names, metadata_names)
  metadata_missing_in_mzml <- setdiff(metadata_names, mzml_files_names)
  
  
  if(length(file_list_tot) != length(metadata_names) ||
     setequal(mzml_files_names, metadata_names) == FALSE){
    
    show_warning_4 <- function(file_list_tot, metadata_table, mzml_missing_in_metadata, metadata_missing_in_mzml) {
      
      ui <- fluidPage(
        titlePanel("Action Required"),
        
        fluidRow(
          column(
            width = 12,
            
            if (length(file_list_tot) != length(metadata_names)) {
              div(class = "alert alert-danger", role = "alert",
                  "⚠ The number of mzML files does not match the number of samples (excluding diluted QC samples) listed in the Metadata. Please correct this before continuing."
              )
            },
            
            if (setequal(mzml_files_names, metadata_names) == FALSE) {
              div(class = "alert alert-danger", role = "alert",
                  "⚠ The mzML file names do not match the sample names (excluding diluted QC samples) listed in the Metadata. Please correct this before continuing."
              )
            },
            
            div(class = "alert alert-warning", role = "alert",
                HTML(paste0(
                  "<b>n mzML files</b> = ", length(file_list_tot), "<br>",
                  "<b>n samples in metadata_table</b> = ", length(metadata_names)
                ))
            ),
            
            div(class = "alert alert-warning", role = "alert",
                HTML(paste0(
                  "<b>mzML names missing in Metadata sample names :</b> ",
                  if (length(mzml_missing_in_metadata) == 0) "None" else paste(mzml_missing_in_metadata, collapse = " ; "), "<br>",
                  "<b>Metadata sample names missing in mzML names :</b> ",
                  if (length(metadata_missing_in_mzml) == 0) "None" else paste(metadata_missing_in_mzml, collapse = " ; ")
                ))
            ),
            
            div(class = "alert alert-success", role = "alert",
                "✔ Once this step is complete, the initialisation is finished. Please return to the code."
            ),
            
            br(),
            actionButton("continue", "Continue", class = "btn-primary")
          )
        )
      )
      
      server <- function(input, output, session) {
        observeEvent(input$continue, {
          stopApp(TRUE)
        })
      }
      
      runApp(shinyApp(ui, server), launch.browser = TRUE)
    }
    
    show_warning_4(file_list_tot, metadata_table, mzml_missing_in_metadata, metadata_missing_in_mzml) # Show the warning to the operator
    
    validate <- FALSE
    
  }else{validate <- TRUE}
  
}
